name: Download ProbTS Dataset and Upload to NAS

on:
  workflow_dispatch:  # 手动触发

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        pip install .
        pip uninstall -y probts

    # 4. 下载数据集
    - name: Download ProbTS datasets
      run: |
        mkdir data
        python probts/utils/download_datasets.py --data_path=data # 下载所有数据集

    # 5. 安装 cifs-utils 以支持 Samba
    - name: Install cifs-utils
      run: sudo apt-get install -y cifs-utils

    # 6. 挂载 NAS 的 Samba 共享目录
    - name: Mount NAS Samba share
      run: |
        sudo mkdir -p /mnt/nas
        sudo mount -t cifs ${{ secrets.SAMBA_SHARE }} /mnt/nas -o username=${{ secrets.SAMBA_USER }},password=${{ secrets.SAMBA_PASSWORD }},port=20445
    # 7. 将数据集上传到 NAS
    - name: Upload datasets to NAS
      run: |
        sudo rsync -av --progress data /mnt/nas/probts_data

    # 8. 卸载 NAS 的 Samba 共享目录
    - name: Unmount NAS Samba share
      run: |
        sudo umount /mnt/nas
