name: Download ProbTS Dataset and Upload to NAS

on:
  workflow_dispatch:  # 手动触发

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        pip install gdown kagglehub
        # pip uninstall -y probts

    # 4. 下载数据集
    - name: Download ProbTS datasets
      run: |
        mkdir data
        python probts/utils/download_datasets.py --data_path=data # 下载所有数据集
        echo "----------------"
        du -hd 1 data
        echo "----------------"
    # 5. 打包 data 目录并分卷
    - name: Pack and split data directory
      run: |
        tar -cf - data | split -b 500M - data_part_
     # 6. 上传分卷为 Artifacts
    - name: Upload split files as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: probts-data
        path: |
          data_part_*
          
